# Generated by Django 5.0 on 2024-02-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console_app', '0002_rename_bundle_amount_userprofile_bundle_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtransaction',
            name='account_email',
        ),
        migrations.RemoveField(
            model_name='newtransaction',
            name='transaction_day',
        ),
        migrations.RemoveField(
            model_name='newtransaction',
            name='transaction_month',
        ),
    ]
