# Generated by Django 5.0 on 2024-02-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_app', '0004_notice_customuser_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
