# Generated by Django 5.0 on 2024-08-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_app', '0005_alter_customuser_approval_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('bundle_volume', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
