# Generated by Django 5.0 on 2024-08-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_app', '0006_bundleprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='creditinghistory',
            name='channel',
            field=models.CharField(choices=[('Paystack', 'Paystack'), ('Manual', 'Manual')], default='Manual', max_length=100),
        ),
        migrations.AddField(
            model_name='creditinghistory',
            name='credited',
            field=models.BooleanField(default=False),
        ),
    ]
